{% set name = "python-mimeparse" %}
{% set version = "1.6.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_val = "76e4b03d700a641fd7761d3cd4fdbbdcd787eade1ebfac43f877016328334f78" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ hash_val }}

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - mimeparse

about:
  home: https://github.com/dbtsai/python-mimeparse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A module provides basic functions for parsing mime-type names and matching them against a list of media-ranges.'
  dev_url: https://github.com/dbtsai/python-mimeparse
  doc_url: https://github.com/dbtsai/python-mimeparse

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
